// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package keycloak

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson79a3de99DecodeGithubComAzukaKeycloakAdminGoKeycloak(in *jlexer.Lexer, out *MultivaluedHashMap) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "empty":
			out.Empty = bool(in.Bool())
		case "loadFactor":
			out.LoadFactor = float64(in.Float64())
		case "threshold":
			out.Threshold = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson79a3de99EncodeGithubComAzukaKeycloakAdminGoKeycloak(out *jwriter.Writer, in MultivaluedHashMap) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Empty {
		const prefix string = ",\"empty\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Empty))
	}
	if in.LoadFactor != 0 {
		const prefix string = ",\"loadFactor\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(in.LoadFactor))
	}
	if in.Threshold != 0 {
		const prefix string = ",\"threshold\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.Threshold))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MultivaluedHashMap) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson79a3de99EncodeGithubComAzukaKeycloakAdminGoKeycloak(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MultivaluedHashMap) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson79a3de99EncodeGithubComAzukaKeycloakAdminGoKeycloak(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MultivaluedHashMap) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson79a3de99DecodeGithubComAzukaKeycloakAdminGoKeycloak(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MultivaluedHashMap) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson79a3de99DecodeGithubComAzukaKeycloakAdminGoKeycloak(l, v)
}
